Pr Checkpoint 2
davidimbong/HRIS pull request #2
Opened 2022-12-12 06:35 UTC by davidimbong

2022-12-13 08:57 UTC, sherwincatli requested changes

2022-12-13 08:57 UTC, sherwincatli commented on app/src/main/java/com/example/hris/ui/profile/UpdateProfileFragment.kt
> +    }
Will this portion be duplicated for every screen? A better approach would be to create a Base Activity/Fragment class that will handle displaying and dismissing the dialog,

It's also not a good idea to handle navigation inside the block that handles `.HIDE`. What if you have multiple API calls inside the screen? Dialog state and navigation should be handled separately. Single Responsibility Principle.

2022-12-13 08:57 UTC, sherwincatli commented on app/src/main/java/com/example/hris/ui/profile/ProfileFragment.kt
> +                val emailAddress = it.emailAddress.hideEmail()
This could be done inside the ViewModel. Just create a UIModel class that contains these fields. The logic should be inside the VM layer so that the UI layer's concerns only with just displaying the data.

2022-12-13 08:59 UTC, davidimbong commented on app/src/main/java/com/example/hris/ui/profile/UpdateProfileFragment.kt
> +    }
noted sir

2022-12-14 03:49 UTC, davidimbong commented on app/src/main/java/com/example/hris/ui/profile/ProfileFragment.kt
> +                val emailAddress = it.emailAddress.hideEmail()
commited sir

2022-12-14 03:58 UTC, sherwincatli requested changes

2022-12-14 03:58 UTC, sherwincatli commented on app/src/main/java/com/example/hris/ui/profile/ProfileFragment.kt
> +            val userProfile = viewModel.getProfile()
This is a little bit redundant. Inside this `.observe` block, you already have access to `UserData` that can be turned into a `Profile` object. Just create a LiveData that contains the `Profile` object and observe that instead.

2022-12-15 02:42 UTC, sherwincatli approved these changes

2022-12-15 02:44 UTC, merged